version: '3.9'

networks:
  loki:

services:
  grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      networks:
        - loki

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - "/var/log:/var/log"
      - "./promtail/promtail-config.yaml:/etc/promtail/config.yml"
      - "./tmp:/tmp"
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki