version: '3.9'

networks:
  loki:

services:
  grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      networks:
        - loki

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    ports:
      - 9080:9080
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
      - ./logs_s3:/s3/logs
      - ./tmp:/tmp
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki