server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: s3
  static_configs:
  - targets:
      - localhost
    labels:
      job: s3_alb
      __path__: /s3/logs/**/*.log.gz
  pipeline_stages:
    - regex: 
        source: s3_alb
        expression: >-
          ^(?s)(?P<type>\S+?) 
          (?P<time>\S+?) 
          (?P<elb>\S+?) 
          (?P<client_port>\S+?) 
          (?P<target_port>\S+?) 
          (?P<request_processing_time>\S+?) 
          (?P<target_processing_time>\S+?) 
          (?P<response_processing_time>\S+?) 
          (?P<elb_status_code>\S+?) 
          (?P<target_status_code>\S+?) 
          (?P<received_bytes>\S+?) 
          (?P<sent_bytes>\S+?) 
          \"(?P<request_method>\S+?) 
          (?P<request_url>\S+?) 
          (?P<request_protocol>\S+?)\" 
          \"(?P<user_agent>.*?)\" 
          (?P<ssl_cipher>\S+?) 
          (?P<ssl_protocol>\S+?) 
          (?P<target_group_arn>\S+?) 
          \"(?P<trace_id>\S+?)\" 
          \"(?P<domain_name>\S+?)\" 
          \"(?P<chosen_cert_arn>\S+?)\" 
          (?P<matched_rule_priority>\S+?) 
          (?P<request_creation_time>\S+?) 
          \"(?P<actions_executed>\S+?)\" 
          \"(?P<redirect_url>\S+?)\" 
          \"(?P<error_reason>\S+?)\" 
          \"(?P<target_port_list>\S+?)\" 
          \"(?P<target_status_code_list>\S+?)\" 
          \"(?P<classification>\S+?)\" 
          \"(?P<reason_classification>\S+?)\"$
    - labels:
        type: 
        time: 
        elb: 
        client_port: 
        target_port: 
        request_processing_time: 
        target_processing_time: 
        response_processing_time: 
        elb_status_code: 
        target_status_code: 
        received_bytes: 
        sent_bytes: 
        request_method: 
        request_url: 
        request_protocol: 
        user_agent: 
        ssl_cipher: 
        ssl_protocol: 
        target_group_arn: 
        trace_id: 
        domain_name: 
        chosen_cert_arn: 
        matched_rule_priority: 
        request_creation_time: 
        actions_executed: 
        redirect_url: 
        error_reason: 
        target_port_list: 
        target_status_code_list: 
        classification: 
        reason_classification: 